### ISSUE TITLE
文档build报错

### ISSUE THREAD

**Issue by swjmy** [elasticjob/elastic-job-doc#1]
在elastic-job-lite-doc目录下执行hugo server -D发生如下报错：
`Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/Users/jimingyao/Documents/es-job/elastic-job-doc/elastic-job-doc/elastic-job-lite-doc/themes/hugo-theme-learn/layouts/_default/list.html:6:16": execute of template failed: template: _default/list.html:6:16: executing "_default/list.html" at <index .Site.Sections...>: error calling index: cannot index slice/array with type string`

**Comment by terrymanu** [comment]
I think that caused by your hugo version.
I am using v0.38 and it is fine.
